# Generated by Django 4.2.3 on 2023-07-19 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='author_to_user', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='дата игры/матча')),
                ('venue', models.CharField(max_length=100, verbose_name='место проведения')),
                ('result', models.CharField(max_length=100, verbose_name='результат матча')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('photo', models.ImageField(upload_to='players/', verbose_name='фото')),
                ('position', models.CharField(max_length=100, verbose_name='позиция')),
                ('age', models.PositiveIntegerField(verbose_name='возраст')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название спорта')),
                ('image', models.ImageField(upload_to='sports/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'спорт',
                'verbose_name_plural': 'спорты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название команды')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='логотип')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_to_country', to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(blank=True, null=True, verbose_name='голы')),
                ('points', models.PositiveIntegerField(blank=True, null=True, verbose_name='очки')),
                ('games_played', models.PositiveIntegerField(blank=True, null=True, verbose_name='игр сыграно')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.game', verbose_name='игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player', verbose_name='игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'ститистика',
                'verbose_name_plural': 'статистики',
                'ordering': ('player', 'goals'),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team', verbose_name='команда'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='статья')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_to_author', to='main.author', verbose_name='автор')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_team1', to='main.team', verbose_name='команда 1'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_team2', to='main.team', verbose_name='команда 2'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.game', verbose_name='игра')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.stat', verbose_name='статистика')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'анализ',
                'verbose_name_plural': 'анализы',
                'ordering': ('game',),
            },
        ),
    ]
