# Generated by Django 4.2.3 on 2023-08-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-date_time',), 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publication_date',), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
