# Generated by Django 4.2.3 on 2023-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='логотип'),
        ),
    ]
