# Generated by Django 4.2.4 on 2023-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='избранный'),
        ),
    ]
